
# Final RDF4J server SPARQL endpoint to load the BioLink RDF
# triplestore_url: https://graphdb.dumontierlab.com/repositories/test-dqa
# triplestore_url: https://graphdb.dumontierlab.com/repositories/test-dqa/statements

# To test different triplestores

triplestore_url: https://graphdb.dumontierlab.com/repositories/test/statements

# triplestore_url: http://graphdb:7200/repositories/test/statements
# triplestore_url: http://blazegraph:8080/bigdata/sparql
# triplestore_url: http://virtuoso:8890/sparql

triplestore_username: import_user

# triplestore_password: password

output_graph_uri:  https://w3id.org/d2s/graph/dqa

# analyzed_sparql_endpoint: http://sparql.wikipathways.org/sparql
analyzed_sparql_endpoint: https://graphdb.dumontierlab.com/repositories/test-dqa
analyzed_graph_uri: https://w3id.org/data2services/graph/biolink/hgnc


rdfunit_schema: https://www.w3.org/2012/pyRdfa/extract?uri=http://vocabularies.wikipathways.org/wp#
# Don't work:
# rdfunit_schema: https://raw.githubusercontent.com/biolink/biolink-model/master/biolink-model.owl


fairsharing_metrics_url: https://fairsharing.org/biodbcore-000015 # ChEMBL
# fairsharing_metrics_url: https://fairsharing.org/FAIRsharing.29we0s # HGNC (don't work)
