
# Final RDF4J server SPARQL endpoint to load the BioLink RDF
triplestore_url: http://graphdb.dumontierlab.com/repositories/test/statements
triplestore_username: dba
triplestore_password: password

graph_uri: https://w3id.org/data2services/graph/biolink/stitch

cwl_dir:
  class: Directory
  path: ..

cwl_workflow_filename: workflow-load-rdf.cwl
