
# Final RDF4J server SPARQL endpoint to load the BioLink RDF
# triplestore_url: http://graphdb.dumontierlab.com/repositories/test-dqa
triplestore_url: http://graphdb.dumontierlab.com/repositories/test-dqa/statements

triplestore_username: import_user
triplestore_password: password

graph_uri:  https://w3id.org/data2services/graph/biolink/hgnc

# cwl_dir:
#   class: Directory
#   path: ..

# cwl_workflow_filename: workflow-load-rdf.cwl
