---
apiVersion: batch/v1
kind: Job
metadata:
  name: calrissian-xml2rdf
spec:
  template:
    spec:
      containers:
      - name: calrissian
        image: dukegcb/calrissian:latest
        command: ["calrissian"]
        args:
          - "--stdout"
          - "/data/output-data/output.json"
          - "--stderr"
          - "/data/output-data/stderr.log"
          - "--max-ram"
          - "16G"
          - "--max-cores"
          - "8"
          - "--tmp-outdir-prefix"
          - "/data/tmpout/"
          - "--outdir"
          - "/data/output-data/"
          - "--usage-report"
          - "/data/output-data/usage.json"
          - "/data/d2s-project-template/d2s-core/cwl/workflows/graphdb-workflow-xml.cwl"
          - "/data/d2s-project-template/datasets/drugbank/config-transform-graphdb-xml-drugbank.yml"
        volumeMounts:
        - mountPath: /data
          name: pv-test-vincent
          subPath: calrissian
        env:
        - name: CALRISSIAN_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      restartPolicy: Never
      volumes:
      - name: pv-test-vincent
        persistentVolumeClaim:
          claimName: pvc-mapr-projects-test-vincent