version: "3"

services:

  virtuoso:
    image: tenforce/virtuoso
    restart: unless-stopped
    volumes:
      - /data/d2s-workspace/virtuoso:/data
      - /tmp/d2s-workspace:/tmp
    ports:
      - 8891:8890
      - 1111:1111
    environment:
      - VIRTUAL_HOST=d2s-virtuoso.137.120.31.101.nip.io # for IDS node1
      - VIRTUAL_PORT=8890
      - DBA_PASSWORD=dba
      - SPARQL_UPDATE=true
      - DEFAULT_GRAPH=https://w3id.org/data2services/graph
      - VIRT_Parameters_DirsAllowed=., /usr/local/virtuoso-opensource/share/virtuoso/vad, /usr/local/virtuoso-opensource/var/lib/virtuoso/db
      - VIRT_VDB_VDBDisconnectTimeout=7200000
      - VIRT_Client_SQL_QUERY_TIMEOUT=14400000
      - VIRT_CLient_SQL_TXN_TIMEOUT=14400000
      - VIRT_SPARQL_MaxQueryCostEstimationTime=0
      - VIRT_SPARQL_MaxQueryExecutionTime=14400
      # - VIRT_SPARQL_DefaultQuery=select distinct ?Concept where {[] a ?Concept} LIMIT 100
    networks:
      - network


  drill:
    image: vemonet/apache-drill
    restart: unless-stopped
    ports:
      - 8048:8047
      - 31011:31010
    tty: true
    volumes:
      - /data/d2s-workspace:/data:ro
      # - /data/d2s-workspace:/data:ro
    networks:
      - network


  graphdb:
    build:
      context: ./support/graphdb
      dockerfile: Dockerfile
      args:
        version: 8.10.1
    # build: ./support/graphdb
    restart: unless-stopped
    volumes:
      - /data/d2s-workspace/graphdb:/opt/graphdb/home
      - /data/d2s-workspace/graphdb-import:/root/graphdb-import
    ports:
      - 7200:7200
    networks:
      - network


  postgres:
    image: postgres:11
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    networks:
      - network


  # http://localhost:8889/bigdata/#splash
  # https://hub.docker.com/r/lyrasis/blazegraph
  blazegraph:
    restart: unless-stopped
    image: lyrasis/blazegraph:2.1.5
    volumes:
      # - /data/d2s-workspace/RWStore.properties:/RWStore.properties
      - /data/d2s-workspace:/data
    ports:
      - 8889:8080
    # environment:
    #   - BLAZEGRAPH_UID=$BLAZEGRAPH_UID
    #   - BLAZEGRAPH_GID=$BLAZEGRAPH_GID
    networks:
      - network


  # Pull Data2Services images
  d2s-download:
    image: umids/d2s-download:latest

  d2s-sparql-operations:
    image: umids/d2s-sparql-operations:latest

  autor2rml:
    image: umids/autor2rml:latest

  r2rml:
    image: umids/r2rml:latest

  xml2rdf:
    image: umids/xml2rdf:latest

  rdf-upload:
    image: umids/rdf-upload:latest

  

networks:
  network:
    driver: bridge



# docker exec -it docker-compose_virtuoso_1 bash
# isql-v -U dba -P password
# ld_dir('output', '*.nq', 'http://test/');
# rdf_loader_run();

# One liner virtuoso bulk load:
#docker exec -it docker-compose_virtuoso_1 isql-v -U dba -P password exec="ld_dir('/usr/local/virtuoso-opensource/var/lib/virtuoso/db/output', '*.nq', 'http://test/'); rdf_loader_run();"
#docker exec -it docker-compose_virtuoso_1 isql-v -U dba -P password exec="ld_dir('output', '*.nq', 'http://test/'); rdf_loader_run();"

# Reset triplestore:
#docker exec -it docker-compose_virtuoso_1 isql-v -U dba -P password exec="RDF_GLOBAL_RESET ();"

# Try to load with RdfUpload
# docker run -it --rm --net docker-compose_network -v /data/d2s-workspace/output:/data umids/rdf-upload -if "/data" -url "http://virtuoso:8890" -un "dba" -pw "password"

# sparql-operations works though
# docker run -it --net docker-compose_network --rm umids/d2s-sparql-operations -op select -sp "select distinct ?Concept where {[] a ?Concept} LIMIT 1000" -ep "http://virtuoso:8890/sparql"
