version: "3"

services:

  virtuoso:
    environment:
      - VIRTUAL_HOST=virtuoso.137.120.31.102.nip.io # for IDS node2
      - VIRTUAL_PORT=8890
      - DBA_PASSWORD=dba

  drill:
    environment:
      - VIRTUAL_HOST=drill.137.120.31.102.nip.io  # node2
      - VIRTUAL_PORT=8047

  api:
    environment: 
      - ENDPOINT=http://graphdb:7200/repositories/trek
      - VIRTUAL_HOST=api.137.120.31.102.nip.io
    
  filebrowser:
    environment:
      - VIRTUAL_HOST=download.137.120.31.102.nip.io
    #   - VIRTUAL_HOST=download.semanticscience.org
    #   - LETSENCRYPT_HOST=download.semanticscience.org

  into-the-graph:
    image: umids/into-the-graph:translator-trek
    environment:
      - VIRTUAL_HOST=trek.137.120.31.102.nip.io

  notebook:
    environment:
      - VIRTUAL_HOST=notebooks.137.120.31.102.nip.io  # node2

  rmlstreamer:
    environment:
      - VIRTUAL_HOST=rmlstreamer.137.120.31.102.nip.io  # node2
      - VIRTUAL_PORT=8081


  # graphdb:
    # image: ontotext/graphdb:9.1.1-ee
    # environment:
    #   - VIRTUAL_HOST=d2s-graphdb.137.120.31.101.nip.io

  # blazegraph:
    # environment:
    #   # Work for Ubuntu ($UID=1000 and 1000 in $GROUPS)
    #   - BLAZEGRAPH_UID=${UID}
    #   - BLAZEGRAPH_GID=${GID}
    #   - VIRTUAL_HOST=d2s-blazegraph.137.120.31.101.nip.io

  # comunica:
