version: "3"

services:

  virtuoso:
    image: tenforce/virtuoso
    volumes:
      - $PWD/workspace/virtuoso:/data
      # - $PWD/workspace/tmp:/tmp
    ports:
      - 8890:8890
      - 1111:1111
    environment:
      - VIRTUAL_HOST=d2s-virtuoso.137.120.31.101.nip.io # for IDS node1
      - VIRTUAL_PORT=8890
      - DBA_PASSWORD=dba
      - SPARQL_UPDATE=true
      - DEFAULT_GRAPH=https://w3id.org/d2s/graph
      - VIRT_Parameters_DirsAllowed=., /usr/local/virtuoso-opensource/share/virtuoso/vad, /usr/local/virtuoso-opensource/var/lib/virtuoso/db
      - VIRT_VDB_VDBDisconnectTimeout=7200000
      - VIRT_Client_SQL_QUERY_TIMEOUT=14400000
      - VIRT_CLient_SQL_TXN_TIMEOUT=14400000
      - VIRT_SPARQL_ResultSetMaxRows=999999999999999999
      - VIRT_SPARQL_MaxQueryCostEstimationTime=0
      - VIRT_SPARQL_MaxQueryExecutionTime=14400
      # - VIRT_SPARQL_DefaultQuery=select distinct ?Concept where {[] a ?Concept} LIMIT 100
    networks:
      - network
    restart: unless-stopped


  drill:
    image: umids/apache-drill:1.17.0
    # image: umids/apache-drill:1.17.0-100G
    ports:
      - 8048:8047
      - 31011:31010
    tty: true
    volumes:
      - $PWD/workspace/input:/data:ro
      # - $PWD/workspace:/data:ro
    networks:
      - network
    restart: unless-stopped


  graphdb:
    build:
      context: ./support/graphdb
      dockerfile: Dockerfile
      args:
        version: 9.1.1
    # build: ./support/graphdb
    command: -Dgraphdb.home=/opt/graphdb/home -Dgraphdb.workbench.cors.enable=true
    volumes:
      - $PWD/workspace/graphdb:/opt/graphdb/home
      - $PWD/workspace/graphdb-import:/root/graphdb-import
    ports:
      - 7200:7200
    networks:
      - network
    restart: unless-stopped
    # environment:
    #   - VIRTUAL_HOST=d2s-graphdb.137.120.31.101.nip.io


  postgres:
    image: postgres:11
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    networks:
      - network
    restart: unless-stopped


  # http://localhost:8889/bigdata/#splash
  # https://hub.docker.com/r/lyrasis/blazegraph
  blazegraph:
    restart: unless-stopped
    image: lyrasis/blazegraph:2.1.5
    volumes:
      - $PWD/workspace:/data
      # - $PWD/workspace/RWStore.properties:/RWStore.properties
    ports:
      - 8082:8080
    # environment:
    #   # Work for Ubuntu ($UID=1000 and 1000 in $GROUPS)
    #   - BLAZEGRAPH_UID=${UID}
    #   - BLAZEGRAPH_GID=${GID}
    networks:
      - network
    # environment:
    #   # Work for Ubuntu ($UID=1000 and 1000 in $GROUPS)
    #   - BLAZEGRAPH_UID=${UID}
    #   - BLAZEGRAPH_GID=${GID}
    #   - VIRTUAL_HOST=d2s-blazegraph.137.120.31.101.nip.io

  comunica:
    image: umids/comunica-sparql-widget:latest
    ports:
      - 8084:80
    # volumes:
    #   - $PWD/workspace:/data
      # - $PWD/workspace/RWStore.properties:/RWStore.properties
    networks:
      - network
    restart: unless-stopped

  api:
    image: umids/d2s-api:latest
    ports: 
      - 8080:8080
    # environment: 
    #   - ENDPOINT=http://graphdb:7200/repositories/trek
    networks:
      - network
    restart: unless-stopped

  filebrowser:
    image: mohamnag/nginx-file-browser:latest
    ports:
      - 8081:80
    volumes:
      - $PWD/workspace/download/:/opt/www/files/
    restart: unless-stopped
    # environment:
    #   - VIRTUAL_HOST=download.semanticscience.org
    #   - LETSENCRYPT_HOST=download.semanticscience.org

  into-the-graph:
    image: umids/into-the-graph:latest
    ports:
      - 8079:5000
    networks:
      - network
    restart: unless-stopped

  browse-translator-trek:
    image: umids/into-the-graph:translator-trek
    ports:
      - 7202:5000
    networks:
      - network
    restart: unless-stopped

  browse-local-virtuoso:
    image: umids/into-the-graph:local-virtuoso
    ports:
      - 8891:5000
    networks:
      - network
    restart: unless-stopped

  browse-local-graphdb:
    image: umids/into-the-graph:local-graphdb
    ports:
      - 7201:5000
    networks:
      - network
    restart: unless-stopped

  browse-local-blazegraph:
    image: umids/into-the-graph:local-blazegraph
    ports:
      - 8083:5000
    networks:
      - network
    restart: unless-stopped

  proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - network
    restart: unless-stopped

  rmljob:
    image: flink:1.9.1-scala_2.11
    expose:
      - "6123"
    ports:
      - "8078:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    volumes:
      - $PWD/workspace/input:/mnt/data

  rmltask:
    image: flink:1.9.1-scala_2.11
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command: taskmanager
    links:
      - "jobmanager:jobmanager"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    volumes:
      - $PWD/workspace/input:/mnt/data

  # Pull Data2Services images
  d2s-bash-exec:
    image: umids/d2s-bash-exec:latest

  d2s-sparql-operations:
    image: umids/d2s-sparql-operations:latest

  autor2rml:
    image: umids/autor2rml:latest

  r2rml:
    image: umids/r2rml:latest

  xml2rdf:
    image: umids/xml2rdf:latest

  rdf-upload:
    image: umids/rdf-upload:latest

  

networks:
  network:
    driver: bridge



# docker exec -it docker-compose_virtuoso_1 bash
# isql-v -U dba -P password
# ld_dir('output', '*.nq', 'http://test/');
# rdf_loader_run();

# One liner virtuoso bulk load:
#docker exec -it docker-compose_virtuoso_1 isql-v -U dba -P password exec="ld_dir('/usr/local/virtuoso-opensource/var/lib/virtuoso/db/output', '*.nq', 'http://test/'); rdf_loader_run();"
#docker exec -it docker-compose_virtuoso_1 isql-v -U dba -P password exec="ld_dir('output', '*.nq', 'http://test/'); rdf_loader_run();"

# Reset triplestore:
#docker exec -it docker-compose_virtuoso_1 isql-v -U dba -P password exec="RDF_GLOBAL_RESET ();"

# Try to load with RdfUpload
# docker run -it --rm --net docker-compose_network -v $PWD/workspace/output:/data umids/rdf-upload -if "/data" -url "http://virtuoso:8890" -un "dba" -pw "password"

# sparql-operations works though
# docker run -it --net docker-compose_network --rm umids/d2s-sparql-operations -op select -sp "select distinct ?Concept where {[] a ?Concept} LIMIT 1000" -ep "http://virtuoso:8890/sparql"
