apiVersion: v1
kind: Service
# https://docs.openshift.com/enterprise/3.0/architecture/core_concepts/pods_and_services.html
metadata:
  #name: docker-registry      
  labels:
    purpose: d2s-services
  name: d2s-service-drill
  namespace: argo

spec:
  selector:
    service: drill
  portalIP: 172.30.136.123
  ports:
  - nodePort: 0
    port: 31010
    protocol: TCP
    targetPort: 31010
  # Add volumes?
  # volumes:
  # - name: workdir
  #   persistentVolumeClaim:
  #     claimName: data2services-storage


