version: "3"

services:

  # http://localhost:8889/bigdata/#splash
  # https://hub.docker.com/r/lyrasis/blazegraph
  blazegraph:
    image: lyrasis/blazegraph:2.1.5
    volumes:
      # - /data/red-kg/RWStore.properties:/RWStore.properties
      - /data/red-kg:/data
    ports:
      - 8889:8080
    # environment:
    #   - BLAZEGRAPH_UID=$BLAZEGRAPH_UID
    #   - BLAZEGRAPH_GID=$BLAZEGRAPH_GID
    networks:
      - d2s-network

networks:
  d2s-network:
    driver: bridge



# Blazegraph load?
# curl -X POST -H 'Content-Type:text/x-nquads' --data-binary '@data-1.nq' http://localhost:8080/bigdata/sparql

