version: "3"

services:

  virtuoso:
    image: tenforce/virtuoso
    restart: unless-stopped
    volumes:
      - /data/red-kg:/data
    ports: 
      - 8890:8890 
      - 1111:1111
    environment:
      - DBA_PASSWORD=password
      - SPARQL_UPDATE=true
      - DEFAULT_GRAPH=https://w3id.org/data2services/graph
    networks:
      - d2s-network

networks:
  d2s-network:
    driver: bridge



# docker exec -it data2services-transform-biolink_virtuoso_1 bash
# isql-v -U dba -P password
# ld_dir('output', '*.nq', 'http://test/');
# rdf_loader_run();

# One liner virtuoso bulk load:
#docker exec -it data2services-transform-biolink_virtuoso_1 isql-v -U dba -P password exec="ld_dir('/usr/local/virtuoso-opensource/var/lib/virtuoso/db/output', '*.nq', 'http://test/'); rdf_loader_run();"

# Reset triplestore:
#docker exec -it data2services-transform-biolink_virtuoso_1 isql-v -U dba -P password exec="RDF_GLOBAL_RESET ();"
