apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: d2s-workflow-transform-xml-
spec:
  entrypoint: execute-workflow

  # Use existing volume
  volumes:
  - name: workdir
    persistentVolumeClaim:
      claimName: data2services-storage

  arguments:
    parameters:
    - name: dataset
      value: null
    - name: download-username
      value: my-download-username
    - name: sparql-tmp-graph-uri
      value: https://w3id.org/data2services/graph/xml2rdf
    - name: sparql-tmp-triplestore-url
      value: http://node000002.cluster.ids.unimaas.nl/
    - name: sparql-tmp-triplestore-repository
      value: test
    - name: sparql-tmp-triplestore-username
      value: import_user
    - name: sparql-tmp-triplestore-password
      value: null
    - name: sparql-final-triplestore-url
      value: http://node000002.cluster.ids.unimaas.nl/
    - name: sparql-final-triplestore-repository
      value: test
    - name: sparql-final-triplestore-username
      value: import_user
    - name: sparql-final-triplestore-password
      value: null
    - name: sparql-final-graph-uri
      value: https://w3id.org/data2services/graph/biolink
    - name: sparql-tmp-service-url
      value: repository:test
    - name: sparql-insert-metadata-path
      value: null
    - name: sparql-transform-queries-path
      value: null

  templates:
  - name: execute-workflow
    steps:
    # - - name: download-files
    #     template: d2s-download
    - - name: run-xml2rdf
        template: xml2rdf
    - - name: run-rdf-upload
        template: rdf-upload
    - - name: sparql-insert-metadata
        template: d2s-sparql-operations
        arguments:
          parameters:
          - name: sparql-queries-path
            value: "{{workflow.parameters.sparql-insert-metadata-path}}"
          - name: sparql-input-graph
            value: "{{workflow.parameters.sparql-tmp-graph-uri}}"
          - name: sparql-output-graph
            value: "{{workflow.parameters.sparql-final-graph-uri}}"
          - name: sparql-service-url
            value: "{{workflow.parameters.sparql-tmp-service-url}}"
          - name: sparql-triplestore-url
            value: "{{workflow.parameters.sparql-final-triplestore-url}}"
          - name: sparql-triplestore-repository
            value: "{{workflow.parameters.sparql-final-triplestore-repository}}"
          - name: sparql-triplestore-username
            value: "{{workflow.parameters.sparql-final-triplestore-username}}"
          - name: sparql-triplestore-password
            value: "{{workflow.parameters.sparql-final-triplestore-password}}"
    - - name: sparql-transform-queries
        template: d2s-sparql-operations
        arguments:
          parameters:
          - name: sparql-queries-path
            value: "{{workflow.parameters.sparql-transform-queries-path}}"
          - name: sparql-input-graph
            value: "{{workflow.parameters.sparql-tmp-graph-uri}}"
          - name: sparql-output-graph
            value: "{{workflow.parameters.sparql-final-graph-uri}}"
          - name: sparql-service-url
            value: "{{workflow.parameters.sparql-tmp-service-url}}"
          - name: sparql-triplestore-url
            value: "{{workflow.parameters.sparql-final-triplestore-url}}"
          - name: sparql-triplestore-repository
            value: "{{workflow.parameters.sparql-final-triplestore-repository}}"
          - name: sparql-triplestore-username
            value: "{{workflow.parameters.sparql-final-triplestore-username}}"
          - name: sparql-triplestore-password
            value: "{{workflow.parameters.sparql-final-triplestore-password}}"
    - - name: sparql-compute-hcls-stats
        template: d2s-sparql-operations
        arguments:
          parameters:
          - name: sparql-queries-path
            value: https://github.com/MaastrichtU-IDS/d2s-transform-repository/tree/master/sparql/compute-hcls-stats
          - name: sparql-input-graph
            value: "{{workflow.parameters.sparql-final-graph-uri}}"
          - name: sparql-output-graph
            value: "{{workflow.parameters.sparql-final-graph-uri}}"
          - name: sparql-service-url
            value: "{{workflow.parameters.sparql-tmp-service-url}}"   # TODO: remove?
          - name: sparql-triplestore-url
            value: "{{workflow.parameters.sparql-final-triplestore-url}}"
          - name: sparql-triplestore-repository
            value: "{{workflow.parameters.sparql-final-triplestore-repository}}"
          - name: sparql-triplestore-username
            value: "{{workflow.parameters.sparql-final-triplestore-username}}"
          - name: sparql-triplestore-password
            value: "{{workflow.parameters.sparql-final-triplestore-password}}"


  - name: d2s-download
    container:
      image: umids/d2s-download:latest
      args: [ "--download-datasets", "{{workflow.parameters.dataset}}", "--working-path", "/data/{{workflow.parameters.dataset}}/input",
      "--username", "{{workflow.parameters.download-username}}"] 
      volumeMounts:
      - name: workdir
        mountPath: /data

  - name: xml2rdf
    container:
      image: umids/xml2rdf:latest
      args: [ "-i", "/data/{{workflow.parameters.dataset}}/input/{{workflow.parameters.dataset}}/**/*.xml*", 
        "-o", "/data/{{workflow.parameters.dataset}}/output/rdf_output.nq.gz", "-g", "{{workflow.parameters.sparql-tmp-graph-uri}}" ]
      volumeMounts:
      - name: workdir
        mountPath: /data

  - name: rdf-upload
    container:
      image: umids/rdf-upload:latest
      args: ["-url", "{{workflow.parameters.sparql-tmp-triplestore-url}}", 
      "-rep", "{{workflow.parameters.sparql-tmp-triplestore-repository}}", 
      "-if", "/data/{{workflow.parameters.dataset}}/output/rdf_output.nq", 
      "-un", "{{workflow.parameters.sparql-tmp-triplestore-username}}", "-pw", "{{workflow.parameters.sparql-tmp-triplestore-password}}"]
      volumeMounts:
      - name: workdir
        mountPath: /data

  - name: d2s-sparql-operations
    inputs:
      parameters:
      - name: sparql-queries-path
      - name: sparql-input-graph
      - name: sparql-output-graph
      - name: sparql-service-url
      - name: sparql-triplestore-url
      - name: sparql-triplestore-repository
      - name: sparql-triplestore-username
      - name: sparql-triplestore-password
    container:
      image: umids/d2s-sparql-operations:latest
      args: ["-ep", "{{inputs.parameters.sparql-triplestore-url}}", 
        "-rep", "{{inputs.parameters.sparql-triplestore-repository}}", 
        "-op", "update", "-f", "{{inputs.parameters.sparql-queries-path}}",
        "-un", "{{inputs.parameters.sparql-triplestore-username}}", 
        "-pw", "{{inputs.parameters.sparql-triplestore-password}}",
        "--var-input", "{{inputs.parameters.sparql-input-graph}}",
        "--var-output", "{{inputs.parameters.sparql-output-graph}}", 
        "--var-service", "{{inputs.parameters.sparql-service-url}}", ]