apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: d2s-workflow-transform-csv-
spec:
  entrypoint: execute-workflow

  volumes:
  - name: workdir
    persistentVolumeClaim:
      claimName: data2services-storage

  arguments:
    parameters:
    - name: dataset
      value: null
    - name: download_username
      value: my_download_username
    - name: sparql_tmp_graph_uri
      value: https://w3id.org/data2services/graph/autor2rml
    - name: sparql_tmp_triplestore_url
      value: http://node000002.cluster.ids.unimaas.nl/
    - name: sparql_tmp_triplestore_repository
      value: test
    - name: sparql_tmp_triplestore_username
      value: import_user
    - name: sparql_tmp_triplestore_password
      value: null
    - name: sparql_final_triplestore_url
      value: http://node000002.cluster.ids.unimaas.nl/
    - name: sparql_final_triplestore_repository
      value: test
    - name: sparql_final_triplestore_username
      value: import_user
    - name: sparql_final_triplestore_password
      value: null
    - name: sparql_final_graph_uri
      value: https://w3id.org/data2services/graph/biolink
    - name: sparql_tmp_service_url
      value: repository:test
    - name: sparql_insert_metadata_path
      value: null
    - name: sparql_transform_queries_path
      value: null


  templates:
  - name: execute-workflow
    steps:
    - - name: download-files
        template: d2s-download
    - - name: drill
        template: apache-drill
    - - name: run-autor2rml
        template: autor2rml
        arguments:
          parameters:
          - name: input_data_jdbc
            value: "jdbc:drill:drillbit={{steps.drill.ip}}:31010"


  - name: d2s-download
    container:
      image: umids/d2s-download:latest
      args: [ "--download-datasets", "{{workflow.parameters.dataset}}", "--working-path", "/data/{{workflow.parameters.dataset}}/input",
      "--username", "{{workflow.parameters.download_username}}"] 
      volumeMounts:
      - name: workdir
        mountPath: /data

  - name: apache-drill
    daemon: true                        # start influxdb as a daemon
    container:
      image: umids/apache-drill:latest
      volumeMounts:
        - name: workdir
          mountPath: /data # readonly?
      readinessProbe:  # wait for readinessProbe to succeed
        httpGet:
          path: /
          port: 8047
        initialDelaySeconds: 5
        #timeoutSeconds: 1

  - name: autor2rml
    inputs:
      parameters:
      - name: input_data_jdbc
    container:
      image: umids/autor2rml:latest
      args: ["-j", "{{inputs.parameters.input_data_jdbc}}", 
      "-o", "/data/{{workflow.parameters.dataset}}/output/mapping.trig", "-d", "/data/{{workflow.parameters.dataset}}/input",
      "-b", "https://w3id.org/data2services/", "-g", "{{workflow.parameters.sparql_tmp_graph_uri}}"]
      volumeMounts:
      - name: workdir
        mountPath: /data