name: Run Data Quality Analysis Assessment CWL workflow

on:
  push:
    branches: [ master ]

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cwlref-runner
        mkdir -p /data/dqa-workspace/output/tmp-outdir
        echo "triplestore_password: ${{ secrets.TRIPLESTORE_PASSWORD }}" > support/config-cwl-dqa.yml
    
    - name: Run CWL workflow
      run: |
        cwl-runner --custom-net d2s-core_network --outdir /data/dqa-workspace/output --tmp-outdir-prefix=/data/dqa-workspace/output/tmp-outdir/ --tmpdir-prefix=/data/dqa-workspace/output/tmp-outdir/tmp- workflows/workflow-dqa.cwl support/config-cwl-dqa.yml

    - name: Upload DQA output artifact
      uses: actions/upload-artifact@v1
      with:
        name: dqa-output
        path: /data/dqa-workspace/output
